# This is an example of what an '_config.yml' file should look like
# when using jekyll-shell-theme. You should use this as a guide or
# just copy+paste it and modify some of the content to begin with.

title: Hackertreff-Reutte
email: HackertreffReutte@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A paragraph describing your webpage.
baseurl: "/" # the subpath of your site
url: "https://hackertreff-reutte.com" # the base hostname & protocol for your site
telegram_username: HackertreffReutte
github_username:  Hackertreff-Reutte

# Required plugins for the theme to work properly
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap

# Including jekyll-shell-theme using the jekyll-remote-theme plugin
#remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - sites/homepage.html
  - sites/blog.html
  - sites/telegram.md
  - sites/FAQ.md

# controls how big the shell and font looks
font-size: small # options: [small] or [large]

#excludes files / folders from being build
exclude: [pull_build.sh, vendor/]


#exclude all posts from the sitemap
defaults:
  -
    scope:
      path: '_posts/**'
    values:
      sitemap: true